Improve parallel raster episode
carpentries-incubator/geospatial-python pull request #136
Opened 2023-04-18 13:16 UTC by fnattino

The example we consider in the parallel raster calculation episode is a bit disappointing, since it does not show performance gain with respect to the serial calculation. Also, I thought it was probably a good idea to remove the downloading part from the time profiling, since the the network is probably limiting for most users.

I suggest an example based on median filtering as new use case. The parallel run shows some actual gain with respect to the serial counterpart, and hopefully it is interesting to some people (e.g. for noise reduction).

2023-06-06 20:46 UTC, rbavery commented
@fnattino keen to take a look at this! Is this ready for review?

2023-06-06 20:47 UTC, fnattino commented
It is @rbavery - very happy if would be willing to have a look indeed!

2023-06-11 01:09 UTC, rbavery requested changes
just requesting some small language changes mostly on tense. Looks great @fnattino, thanks for selecting a better example calculation and describing it so well!

2023-06-11 01:09 UTC, rbavery commented on _episodes/11-parallel-raster-computations.md
> +[Median filtering](https://en.wikipedia.org/wiki/Median_filter) is a common noise removal technique, and it consists in
```suggestion
[Median filtering](https://en.wikipedia.org/wiki/Median_filter) is a common noise removal technique which
```

2023-06-11 01:09 UTC, rbavery commented on _episodes/11-parallel-raster-computations.md
> +replacing a pixel intensity with the value computed from the median of the surrounding pixels.
```suggestion
replaces a pixel's value with the median value computed from its surrounding pixels.
```

2023-06-11 01:09 UTC, rbavery commented on _episodes/11-parallel-raster-computations.md
> +multiple lower-resolution versions of the original image, called "overviews", in the same file. This allows to avoid
```suggestion
multiple lower-resolution versions of the original image, called "overviews", in the same file. This allows us to avoid
```

2023-06-11 01:09 UTC, rbavery commented on _episodes/11-parallel-raster-computations.md
> +considered for the median calculation (the so-called "windows"), using the `.rolling()` method. We chose here windows
```suggestion
considered for the median calculation (the so-called "windows"), using the `.rolling()` method. We choose here windows
```

2023-06-12 11:19 UTC, merged