Create overview of workshops in workshops.md
carpentries-incubator/geospatial-python pull request #173
Opened 2024-08-26 08:53 UTC by svenvanderburg

This adds a file `workshops.md` that keeps track of all workshops taught using this lesson material. It would serve to measure the impact of the lesson. I am pretty sure that I miss a lot of past editions, so please update the table!

2024-08-27 07:38 UTC, svenvanderburg commented
Thanks @fnattino :)

2024-10-09 13:26 UTC, svenvanderburg commented
@fnattino any update on this? :)

2025-01-14 15:11 UTC, fnattino requested changes
Hi @svenvanderburg sorry for blocking this for so long. I have added the workshops I am aware of for which the lesson material has been used. I believe this can be merged after these are included.

2025-01-14 15:11 UTC, fnattino commented on workshops.md
> +| 2023-05-08        | Netherlands eScience Center | Online                     |                            |
```suggestion
| 2023-05-08        | Netherlands eScience Center | Online                     |                            |
| 2023-07-13        | Development Seed            | Pasadena, California       | IEEE GRSS-USC MHI 2023 Remote Sensing Summer School |
```

2025-01-20 11:41 UTC, svenvanderburg commented
Great @fnattino I committed your suggestions. I think you can go ahead and merge :)

2025-01-20 13:30 UTC, merged