Vector data
carpentries-incubator/geospatial-python pull request #39
Opened 2021-03-18 17:31 UTC by zyykyy

2021-03-18 17:35 UTC, zyykyy commented
I made changes to the paragraph where it introduced the vector format -shapefile. .shp is the feature shape itself which is one of multiple files for Shapefile format, not contains Coordinate reference system (CRS) information. The CRS information is stored in .prj file. Meanwhile, the .prj file is not mandatory file for a Shapefile. Some shapefiles do not have CRS information.

2021-04-08 21:29 UTC, rbavery requested changes

2021-04-08 21:29 UTC, rbavery commented on _episodes/02-intro-vector-data.md
> +includes the following information:
```suggestion
workshop, we will use the Shapefile format. A Shapefile format consists of multiple
files in the same directory, of which `.shp`, `.shx`, and `.dbf` files are mandatory. Other non-mandatory but very important files are `.prj` and `shp.xml` files. 

- The `.shp` file stores the feature geometry itself 
- `.shx` is a positional index of the feature geometry to allow quickly searching forwards and backwards the geographic coordinates of each vertex in the vector
- `.dbf` contains the tabular attributes for each shape. 
- `.prj` file indicates the Coordinate reference system (CRS)
- `.shp.xml` contains the Shapefile metadata. 

Together, the Shapefile includes the following information:
```

2021-04-08 21:31 UTC, rbavery commented
Thanks so much @zyykyy for the excellent description, this will be quite useful for folks that are new to shapefiles.

2021-04-08 21:31 UTC, merged